[build]
  command = "ng build"
  publish = "dist/image-placeholder/browser"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  included_files         = ["node_modules/sharp/**/*"]   # ‚Üê NEW

[[redirects]]
  from   = "/image"
  to     = "/.netlify/functions/image"
  status = 200
  force  = true

[[redirects]]
  from   = "/image/"
  to     = "/.netlify/functions/image"
  status = 200
  force  = true

